### ISSUE TITLE
Some mods I think could be added to the pack

### ISSUE THREAD

**Issue by noeppi-noeppi** [sebinside/SkyblockNachfolger#16]
I don't expect all of them to be used. I just wanted to share my thoughts here and suggest some mods you might not have known about.

1. Robotic Parts + ReWIRED:
   This gives the possibility to cut out parts from your body and replace them with electronic pieces. In this way you can become an android. However you need to stay charged with RF. Maybe also crafting recipes with your own body parts are possible (you can get them back if you die). I really like that mod and I think it's used way too less. Also it's not ported so it might be the last chance playing with it.

2. Uppers, HopperDucts
   Two small mods that just make hoppers more convenient. The first one adds upside down hoppers and the second one adds some sort of pipes to extend the hopper out. You're still limited by hopper speed ut I think i nearly game this could be quite handy.

3. Gadgetry
   Gadgetry adds some cool devices that for example activate blocks or pull items in. Also there are simple pipes. And there's a new alloy furnace that can be used as a new recpe type (which is always good when changing recipes)

4. Alternating Flux
   Adds a new cable tier to Immersive engineering that can not be directly attached to machines. It's useful for longer range transport of energy. Might be useful if IE should be used in the later game when the island starts to grow.

5. BuildCraft
   You've probably thought about it already. But I really like that mod and I don't think putting it would be bad for the pack. And you could create custom recipes for assembly and integration table. I'm not sure if BuildCraft can work with Forge Energy in 1.12 but if it doesn't I can easily add that feature to the skateKAPPA mod. And if you're adding BuildCraft maybe also put Iron Tanks in as Iron Chests is in the pack either way.

6. Chisel
   To build better houses in skyblock. I have heard there are such strange people.

7. OC Sensors
   A sensor block for OpenComputers that can scan for blocks and entities.

8. **BedrockCraft**
   Yeah I highlighted this one as I still really like that mod and I'm a bit sad that so few people play with it. It is my mod so sorry for the self advertise (if this term matches here). This mod allows you to break bedrock, generate much energy, create more complex potions and has a few other cool features like wireless redstone. You can create bedrock but at a high cost (ok you'll need to change things here as there's no bedrock generated in a skyblock world). To find out everything this mod does, see https://bitbucket.org/noeppi_noeppi/bedrockcraft/wiki/Home Also this mod will not be ported as LWJGL 3 (which is used by minecraft 1.13+) dropped GLU support, so I can no longer render the spheres. Also with the upcoming 1.17 the mod would no longer make sense as bedrock is no longer located at y=0. I'd be really happy if you could find a use for it.

Download links:
  * Robotic Parts: https://www.curseforge.com/minecraft/mc-mods/roboticparts
  * ReWIRED: https://www.curseforge.com/minecraft/mc-mods/rewired
  * Uppers: https://www.curseforge.com/minecraft/mc-mods/uppers
  * Hopper Ducts: https://www.curseforge.com/minecraft/mc-mods/hopper-ducts
  * Gadgetry Core: https://www.curseforge.com/minecraft/mc-mods/gadgetry-core
  * Gadgetry Machines: https://www.curseforge.com/minecraft/mc-mods/gadgetry-machines
  * Gadgetry Transmission: https://www.curseforge.com/minecraft/mc-mods/gadgetry-machines
  * Alternating Flux: https://www.curseforge.com/minecraft/mc-mods/alternating-flux
  * Buildcraft: https://www.curseforge.com/minecraft/mc-mods/buildcraft
  * Iron Tanks: https://www.curseforge.com/minecraft/mc-mods/iron-tanks
  * Chisel: https://www.curseforge.com/minecraft/mc-mods/iron-tanks
  * OC Sensors: https://www.curseforge.com/minecraft/mc-mods/oc-sensors
  * **BedrockCraft**: https://www.curseforge.com/minecraft/mc-mods/bedrockcraft

**Comment by derNiklaas** [comment]
I would also like to add [AIOT Botania](https://github.com/melanx/AIOTBotania) by @MelanX

**Comment by MelanX** [comment]
> I would also like to add [AIOT Botania](https://github.com/melanx/AIOTBotania) by @MelanX

https://github.com/sebinside/SkyblockNachfolger/pull/11

**Comment by sebinside** [comment]
BedrockCraft and OS Sensors sound interesting, thank you. Most of the other mods were already explicitly excluded (although I did not document this decision...).
